services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: coleta_seletiva
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3306:3306"
    networks:
      - coleta-network
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  coleta-seletiva:
    build: .
    ports:
      - "8080:8080"
    environment:
      - "spring.datasource.url=jdbc:mysql://mysql:3306/coleta_seletiva"
      - "spring.datasource.username=root"
      - "spring.datasource.password=123"
      - "spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver"
      - "spring.flyway.enabled=false"
      - "eureka.client.enabled=false"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - coleta-network
    volumes:
      - ./logs:/app/logs

networks:
  coleta-network:
    driver: bridge

volumes:
  mysql-data:
