name: Continuous Integration

on:
  push:
    branches:
      - staging
      - producao

jobs: 
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  
          java-version: '17'       
